from django.conf import settings
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.contrib import admin

if 'django_comments' in settings.INSTALLED_APPS:
	COMMENT_URLS = 'django_comments.urls'
else:
	COMMENT_URLS = 'django.contrib.coments.urls'
print COMMENT_URLS

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^root/$', views.api_root),
	url(r'^more/', views.more, name='more'),
    url(r'^contact/', views.contact, name='contact'),
	url(r'^profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
	url(r'^profile/(?P<profile_id>\d+)/edit$', views.edit, name='edit'),
	url(r'^signup/', views.signup, name='signup'),
	url(r'^(?P<token>[\w|\W]+)/signup/', views.signup_token, name='signup-token'),
	url(r'^accounts/login/', views.login, name='login'),
	url(r'^logout/', views.logout, name='logout'),
	url(r'^userhome/', views.userhome, name='userhome'),
	url(r'^board/(?P<board>[\w|\W]+)/', views.board, name='board'),
	url(r'^(?P<board>[\w|\W]+)/discussion/', views.discussion, name='discussion'),
	url(r'^(?P<board>[\w|\W]+)/members/', views.members, name='members'),
	url(r'^(?P<board>[\w|\W]+)/files/', views.files, name='files'),
	url(r'^settings/(?P<board>[\w|\W]+)/', views.board_settings, name='board_settings'),
	url(r'^delete/(?P<board>[\w|\W]+)/', views.delete_board, name='delete_board'),
	url(r'^join/(?P<board>[\w|\W]+)/', views.join, name='join'),
	url(r'^leave/(?P<board>[\w|\W]+)/', views.leave_board, name='leave_board'),
	url(r'^boards/', views.boards, name='boards'),
	url(r'^join_board/', views.join_board, name='join-board'),
	url(r'^notifications/', views.notifications, name='notifications'),
	url(r'^add_member/(?P<user_id>\d+)/(?P<board>[\w|\W]+)/', views.add_member, name='add-member'),
	url(r'^makeadmin/(?P<profile_id>\d+)/(?P<board>[\w|\W]+)/$', views.make_admin, name='edit'),
	url(r'^removeadmin/(?P<profile_id>\d+)/(?P<board>[\w|\W]+)/$', views.remove_admin, name='edit'),
	url(r'^deletefeedback/(?P<feedback_id>\d+)/(?P<board>[\w|\W]+)/', views.delete_feedback, name='delete-feedback'),
	url(r'^deletefeedback_fromfeedback/(?P<feedback_id>\d+)/(?P<board>[\w|\W]+)/', views.delete_feedback_from_feedback, name='delete-feedback-from-feedback'),
	url(r'^editfeedback/(?P<feedback_id>\d+)/(?P<board>[\w|\W]+)/', views.edit_feedback, name='edit-feedback'),
	url(r'^upvote/(?P<feedback_id>\d+)/(?P<board>[\w|\W]+)/', views.update_upvote, name='update-upvote'),
	url(r'^downvote/(?P<feedback_id>\d+)/(?P<board>[\w|\W]+)/', views.update_downvote, name='update-downvote'),
	url(r'^editannouncement/(?P<announcement_id>\d+)/$', views.edit_announcement, name='edit-announcement'),\
	url(r'^removeannouncement/(?P<announcement_id>\d+)/(?P<board>[\w|\W]+)/$', views.remove_announcement, name='remove-announcement'),
	url(r'^deletefile/(?P<file_id>\d+)/$', views.delete_file, name='delete-file'),
	url(r'^downloadfile/(?P<file_id>\d+)/$', views.download_file, name='download-file'),
	url(r'^comments/', include(COMMENT_URLS)),
	url(r'^(?P<board>[\w|\W]+)/feedback/(?P<feedback_id>\d+)/', views.feedback, name='feedback'),
	url(r'^deletecomment/(?P<comment_id>\d+)/', views.delete_comment, name='delete-comment'),
	url(r'^editcomment/(?P<comment_id>\d+)/(?P<board>[\w|\W]+)/(?P<feedback_id>\d+)/', views.edit_comment, name='edit-comment'),
	url(r'^feedbacks/comments/post/$', views.post_comment, name='post-comment'), 
	url(r'^feedbacks/comments/', include('django_comments.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

	#API ROOT URLS
	url(r'^organizations/$', views.organization_list.as_view(), name='organization-list'),
	url(r'^organizations/(?P<pk>[0-9]+)/$', views.organization_detail.as_view(), name='organization-detail'),
	url(r'^profiles/$', views.profile_list.as_view(), name='profile-list'),
	url(r'^profiles/(?P<pk>[0-9]+)/$', views.profile_detail.as_view(), name='profile-detail'),
	url(r'^users/$', views.user_list.as_view(), name='user-list'),
	url(r'^users/(?P<pk>[0-9]+)/$', views.user_detail.as_view(), name='user-detail'),
	url(r'^boardss/$', views.board_list.as_view(), name='board-list'),
	url(r'^boardss/(?P<pk>[0-9]+)/$', views.board_detail.as_view(), name='board-detail'),
	url(r'^groups/$', views.group_list.as_view(), name='group-list'),
	url(r'^groups/(?P<pk>[0-9]+)/$', views.group_detail.as_view(), name='group-detail'),
	url(r'^statuses/$', views.status_list.as_view(), name='status-list'),
	url(r'^statuses/(?P<pk>[0-9]+)/$', views.status_detail.as_view(), name='status-detail'),
	url(r'^feedbacks/$', views.feedback_list.as_view(), name='feedback-list'),
	url(r'^feedbacks/(?P<pk>[0-9]+)/$', views.feedback_detail, name='feedback-detail'),
	url(r'^feedbacks/(?P<pk>[0-9]+)/(?P<feedbackuserid>[0-9]+)/$', views.feedback_detail, name='feedback-detail'),
	url(r'^announcements/$', views.announcement_list.as_view(), name='announcement-list'),
	url(r'^announcements/(?P<pk>[0-9]+)/$', views.announcement_detail.as_view(), name='announcement-detail'),
	url(r'^bugs/$', views.bug_list.as_view(), name='bug-list'),
	url(r'^bugs/(?P<pk>[0-9]+)/$', views.bug_detail.as_view(), name='bug-detail'),
	url(r'^feature_requests/$', views.feature_request_list.as_view(), name='feature_request-list'),
	url(r'^feature_requests/(?P<pk>[0-9]+)/$', views.feature_request_detail.as_view(), name='feature_request-detail'),
	url(r'^discussions/$', views.discussion_list.as_view(), name='discussion-list'),
	url(r'^discussions/(?P<pk>[0-9]+)/$', views.discussion_detail.as_view(), name='discussion-detail'),
	url(r'^tags/$', views.tag_list.as_view(), name='tag-list'),
	url(r'^tags/(?P<pk>[0-9]+)/$', views.tag_detail.as_view(), name='tag-detail'),
	url(r'^votes/$', views.vote_list.as_view(), name='vote-list'),
	url(r'^votes/(?P<pk>[0-9]+)/$', views.vote_detail.as_view(), name='vote-detail'),
	url(r'^subscriptions/$', views.subscription_list.as_view(), name='subscription-list'),
	url(r'^subscriptions/(?P<pk>[0-9]+)/$', views.subscription_detail.as_view(), name='subscription-detail'),
	url(r'^comments/$', views.comment_list.as_view(), name='comment-list'),
	url(r'^comments/(?P<pk>[0-9]+)/$', views.comment_detail.as_view(), name='comment-detail'),
	url(r'^files/$', views.file_list.as_view(), name='file-list'),
	url(r'^files/(?P<pk>[0-9]+)/$', views.file_detail.as_view(), name='file-detail'),
	url(r'^email_tokens/$', views.email_token_list.as_view(), name='email-token-list'),
	url(r'^emails_tokens/(?P<pk>[0-9]+)/$', views.email_token_detail.as_view(), name='email-token-detail'),
	url(r'^filess/$', views.file_list.as_view(), name='file-list'),
	url(r'^filess/(?P<pk>[0-9]+)/$', views.file_detail.as_view(), name='file-detail'),
]
